### ISSUE TITLE
Maximum vote strategy

### ISSUE THREAD

**Issue by thomasscovell** [snapshot-labs/snapshot-strategies#1479]
We are looking for a voting strategy that gives a capped number of votes to a wallet.

i.e. Cap is 200K, any user with over 200K votes _only_ gets 200K votes. Any user with less, gets the specific number of votes as they have tokens.

e.g. Wallet A has 250K tokens. Wallet B has 48K tokens.

Wallet A gets 200K votes. Wallet B gets 48K votes.

(Yes this introduces the opportunity for users to split their holdings into multiple votes for higher voting power but this isn't a particular concern due to other factors).

**Comment by ChaituVR** [comment]
Hi @thomasscovell I think you could use this strategy https://snapshot.org/#/strategy/thresholds let me know if you see some problem

Closing this for now, feel free to contact us here https://help.snapshot.org/
