### ISSUE TITLE
Subgraph endpoints failing with 500

### ISSUE THREAD

**Issue by penandlim** [snapshot-labs/snapshot-strategies#1606]
### Expected behavior

[Sablier-v2 playground](https://snapshot.org/#/playground/sablier-v2?query=eyJwYXJhbXMiOnsiYWRkcmVzcyI6IjB4OTdjYjM0MmNmMmY2ZWNmNDhjMTI4NWZiODY2OGY1YTQyMzdiZjg2MiIsImRlY2ltYWxzIjoxOCwic3ltYm9sIjoiREFJIiwicG9saWN5Ijoid2l0aGRyYXdhYmxlLXJlY2lwaWVudCJ9LCJuZXR3b3JrIjoiMSIsInNuYXBzaG90IjoiMjA5MzY0NjgiLCJhZGRyZXNzZXMiOlsiMHg5YWQ3Y2FkNGYxMGQwYzNmODc1YjhhMmZkMjkyNTkwNDkwYzlmNDkxIiwiMHhkOGRBNkJGMjY5NjRhRjlEN2VFZDllMDNFNTM0MTVEMzdhQTk2MDQ1IiwiMHg1MDZDNTZCMjU0MWVGZUNmN0E1MTBFOUEwYzAzODJjQjJGQzY5MDUxIl19)

[balance-of-subgraph playground
](https://snapshot.org/#/playground/balance-of-subgraph?query=eyJwYXJhbXMiOnsic3ViR3JhcGhVUkwiOiJodHRwczovL3N1YmdyYXBoZXIuc25hcHNob3Qub3JnL3N1YmdyYXBoL2FyYml0cnVtLzRSR2JRQ0tWMU5Ob0VKY0szc2h3Z1R2bjY1enNIYUZkcUc5UlB2djI4cUpVIn0sIm5ldHdvcmsiOiIxIiwic25hcHNob3QiOiIyMDkzNjUyMSIsImFkZHJlc3NlcyI6WyIweGU0ZWYyOTU0NWRiMTRlMjUyQWVDMWM2NjBBMDA0ZTI0MDhEYzYyZDIiLCIweGEzYzFjOTE0MDNmMDAyNmI5ZGQwODY4ODJhZGJjOGNkYmMzYjNjZmIiXX0.)

Expected the playgrounds with default values to succeed.

### Actual behavior

Strategies involving a subgraph call fails with 500

```json
 {
  "code": 500,
  "message": "unauthorized",
  "data": "Errors found in subgraphRequest: URL: https://subgrapher.snapshot.org/subgraph/arbitrum/EuZZnhFtdCGqN2Zt7EMGYDqQKNrVuhJL63KAfwvF35bL, Status: 400,  Response: [{\"message\":\"auth error: payment required for subsequent requests for this API key\"}]"
}
```

<img width="728" alt="image" src="https://github.com/user-attachments/assets/08cfc62f-db97-4bf8-83b5-5049fb19ddc5">

### Steps to reproduce the behavior

Visit any playground page of strategies involving the endpoint `subgrapher.snapshot.org`.

**Comment by ChaituVR** [comment]
Thank you! should be working again now :)
