### ISSUE TITLE
Are strategies from other chains, e.g. polygon, L2, or BSC possible?

### ISSUE THREAD

**Issue by TimDaub** [snapshot-labs/snapshot-strategies#235]
Would strategies that get the ERC20 token holder distribution on e.g. Polygon work too? I've looked into the code, but I couldn't find anything that was requesting other chains than mainnet, rinkeby or kovan. But I'd imagine that all that'd be needed is to input the right parameters to e.g. the erc20-balance-of strategy, right? E.g. setting `network` and `provider` correctly: https://github.com/snapshot-labs/snapshot-strategies/blob/2383c3050d40a4527ca81f008af4fafbde3df7b3/src/strategies/erc20-balance-of/index.ts#L14

**Comment by bonustrack** [comment]
@TimDaub Yes Snapshot support most of EVM chains have a look here: https://snapshot.org/#/networks
You can change the network in the space settings, you can also use multiple network as voting power using the voting strategy "multichain" see https://snapshot.org/#/strategy/multichain

**Comment by ChaituVR** [comment]
Closing this for now, please feel free to reopen or create new issue @TimDaub
