### ISSUE TITLE
What is address and Example.json

### ISSUE THREAD

**Issue by ekwelfweer** [snapshot-labs/snapshot-strategies#356]
Hello,

What should i fill the "network", "addresses", and "snapshot" slot in example.json for creating new strategy?

sincerely,
yosep.

**Comment by ChaituVR** [comment]
Hi @ekwelfweer network is the id of the network, you can find your network and chain ID here https://snapshot.org/#/networks
`addresses` is an array, where you can pass your voter addresses (addresses that can give positive voting power)
`snapshot` is the snapshot block number - pick a recent block number of the network


Closing this, for now, feel free to reopen if needed, you can also ask questions on snapshot discord https://discord.snapshot.org/
