### ISSUE TITLE
Unable to activate crucible strategy

### ISSUE THREAD

**Issue by thegostep** [snapshot-labs/snapshot-strategies#37]
While activating the crucible strategy I reach this screen:
<img width="444" alt="image" src="https://user-images.githubusercontent.com/15959632/130581905-7e41c680-8d84-48ed-a069-69f8bc385ee8.png">

When copying the example parameters from [here](https://snapshot.org/#/strategy/crucible-erc20-balance-of) the `add` button becomes inactive.

<img width="444" alt="image" src="https://user-images.githubusercontent.com/15959632/130581516-6421b280-f81d-4b58-8183-7e89d81fb711.png">

**Comment by ChaituVR** [comment]
@thegostep Hello, Can you try adding `symbol` to params, works for me if i add,
```
{
 "symbol": "ABC",
  "crucible_factory": "0x54e0395CFB4f39beF66DBCd5bD93Cca4E9273D56",
  "erc20_address": "0xCD6bcca48069f8588780dFA274960F15685aEe0e",
  "erc20_decimals": 18
}
```

Let me know if that fixes this issue
