### ISSUE TITLE
Art Blocks Strategy

### ISSUE THREAD

**Issue by mattdesl** [snapshot-labs/snapshot-strategies#398]
Hi there, I'm curious about a strategy that uses NFTs from ArtBlocks, which is on a shared contract but with a token ID range between two numbers. So for example, anybody that holds a [Meridian](https://opensea.io/collection/meridian-by-matt-deslauriers) token can vote through that, but if somebody only has other ArtBlocks tokens from the same contract address, they should not be entitled to vote. Happy to open a PR but might need a bit of a guidance in terms of the best approach for this.

**Comment by ChaituVR** [comment]
Hi @mattdesl How many tokens exist in this range? 

Did you try this strategy if you are looking for less number of token IDs https://snapshot.org/#/playground/erc721-with-tokenid-range-weights-simple?query=eyJwYXJhbXMiOnsiYWRkcmVzcyI6IjB4YTdkOGQ5ZWY4ZDhjZTg5OTJkZjMzZDhiOGNmNGFlYmFiZDViZDI3MCIsInN5bWJvbCI6IkxJTktTREFPIiwidG9rZW5JZFdlaWdodFJhbmdlcyI6W3sic3RhcnQiOjIzMzAwMDc0NiwiZW5kIjoyMzMwMDA3NDYsIndlaWdodCI6MX1dfSwibmV0d29yayI6IjEiLCJzbmFwc2hvdCI6MTQyMjM1NTgsImFkZHJlc3NlcyI6WyIweDdkODYzZDc0OTE3MTkxNjg1NjE2MjE3YzhhYjFhNzdlNzNlNzlmMjEiLCIweGIxMTFkYWJiOGVkZDgyNjBiNWMxZTQ3MTk0NWE2MmJlMmVlMjQ0NzAiLCIweDI4NWJkM2E1YzljYWUwMjRkNzBjN2U3MGZjZmM1OWRiMDM2Mzc1NDkiXX0.

**Comment by ChaituVR** [comment]
If it doesn't work I think you may have to create a new strategy that calls `tokensOfOwner` for each address and count the vote if these tokens exist in a given range, I feel this is the best way than `erc721-with-tokenid-range-weights-simple` strategy 🤔

**Comment by ChaituVR** [comment]
You can follow these steps https://docs.snapshot.org/strategies/create to create strategy
