### ISSUE TITLE
"erc20-with-balance" usability

### ISSUE THREAD

**Issue by hjjlxm** [snapshot-labs/snapshot-strategies#539]
### Case
As quoted as a representative strategy in the [official doc](https://docs.snapshot.org/strategies/what-is-a-strategy#other-common-strategies), "[erc20-with-balance](https://snapshot.org/#/playground/erc20-with-balance?query=eyJwYXJhbXMiOnsiYWRkcmVzcyI6IjB4ODRjQThiYzc5OTcyNzJjN0NmQjREMENkM0Q1NWNkOTQyQjNjOTQxOSIsInN5bWJvbCI6IkRJQSIsImRlY2ltYWxzIjoxOH0sIm5ldHdvcmsiOiIxIiwic25hcHNob3QiOiIiLCJhZGRyZXNzZXMiOlsiMHgwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwYmFkZGFkIiwiMHhhNDc4YzI5NzVhYjFlYTg5ZTgxOTY4MTFmNTFhN2I3YWRlMzNlYjExIiwiMHhlRjgzMDVFMTQwYWM1MjAyMjVEQWYwNTBlMmY3MWQ1ZkJjQzU0M2U3IiwiMHhCQTJFN0ZlZDU5N2ZkMEUzZTcwZjUxMzBCY0RiYkZFMDZiQjk0ZmUxIiwiMHhCQTJFN0ZlZDU5N2ZkMEUzZTcwZjUxMzBCY0RiYkZFMDZiQjk0ZmUxIiwiMHg0Qzc5MDlkNkYwMjliM2E1Nzk4MTQzQzg0M0Y0ZjhlNTM0MWEzNDczIiwiMHg4NGNBOGJjNzk5NzI3MmM3Q2ZCNEQwQ2QzRDU1Y2Q5NDJCM2M5NDE5IiwiMHg3MmFjMTc2MGRhZjUyOTg2NDIxYjE1NTJiZGNhMDQ3MDdlNzg5NTBlIl19)" strategy allows the space owner to check the min amount of token required to vote. 

During the test, if I add the parameter **“minBalance”** and set the value to **"10"** where the wallet has only **5** token at snapshot, it still gives 1 voting power.

**Comment by hjjlxm** [comment]
The link is too long, I'll put it in this hyperlink: [erc20-with-balance](https://snapshot.org/#/playground/erc20-with-balance?query=eyJwYXJhbXMiOnsiYWRkcmVzcyI6IjB4QTBiODY5OTFjNjIxOGIzNmMxZDE5RDRhMmU5RWIwY0UzNjA2ZUI0OCIsInN5bWJvbCI6IlVTREMiLCJkZWNpbWFscyI6Nn0sIm5ldHdvcmsiOiIxIiwic25hcHNob3QiOiIiLCJhZGRyZXNzZXMiOlsiMHgwNkYzMDM3QTBmNzUzQzNmRjIxNDBGMTJBMDkzZTYxMjQ1RTUyMzRmIl19)

As instructed by the official doc, using USDC with decimal 6 and passed the "minbalance" to test.

> [Other Common strategies](https://docs.snapshot.org/strategies/what-is-a-strategy#other-common-strategies)

`erc20-with-balance is an example of strategy that checks whether the participant has a minimum amount of token required to vote and assigns all the votes to 1. You need to add the parameter “minBalance” and set it equal to the minimum balance required to vote on a proposal. This value is set to 0 by default. `

**Comment by ChaituVR** [comment]
Maybe the playground link is wrong, i can't see any minbalance in it, i tried adding `minBalance` and it works. [check here](https://snapshot.org/#/playground/erc20-with-balance?query=eyJwYXJhbXMiOnsiYWRkcmVzcyI6IjB4QTBiODY5OTFjNjIxOGIzNmMxZDE5RDRhMmU5RWIwY0UzNjA2ZUI0OCIsInN5bWJvbCI6IlVTREMiLCJkZWNpbWFscyI6NiwibWluQmFsYW5jZSI6Mn0sIm5ldHdvcmsiOiIxIiwic25hcHNob3QiOjE0NTcwMjM3LCJhZGRyZXNzZXMiOlsiMHgwNkYzMDM3QTBmNzUzQzNmRjIxNDBGMTJBMDkzZTYxMjQ1RTUyMzRmIl19) the user got 1 USDT, and if you remove `minBalance` you should see that voting power will be 1

**Comment by hjjlxm** [comment]
Thanks! I think it works.
For people who may seek help like this strategy, I'll comment as below:
1. The token address doesn't need to be checksummed.
2. make sure the param is “minBalance”  not “minbalance”
