### ISSUE TITLE
Create strategy for Orca

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot-strategies#725]
This is a contract ERC1155 that include all the Orca pods https://etherscan.io/token/0x0762aa185b6ed2dca77945ebe92de705e0c37ae3#inventory each pod have their own tokenId. Each token can have multiple holders. We should create a strategy "orca-pod" to give 1 voting power for each holder of a specific tokenId holder. Ideally the weight should be a param, to allow changing vp from 1 to any amount

**Comment by ChaituVR** [comment]
Waiting for confirmation

**Comment by bonustrack** [comment]
It's confirmed
