### ISSUE TITLE
[harmony-staking] Incorrect vote power for 1666700000 on `harmony-testnet.eth`

### ISSUE THREAD

**Issue by MaxMustermann2** [snapshot-labs/snapshot-strategies#803]
### Expected behavior
As on block `192690` of 1666700000 (Harmony test net), the address `0x29c2eC57803f8b695f02613E5FA1749c165c5057` has a voting power of 1e22 wei per the `harmony-staking` strategy.
```bash
$ curl -H "Content-Type: application/json" -d \
'{"method":"hmy_getValidatorsStakeByBlockNumber", "params":[192690],"id":1}' \
https://api.s0.b.hmny.io | jq .result
{
  "0x29c2eC57803f8b695f02613E5FA1749c165c5057": 1e+22
}
```

### Actual behavior
The reported voting power on [this `harmony-testnet.eth` proposal](https://snapshot.org/#/harmony-testnet.eth/proposal/0x3d428acdcc9c4d840f22616f7ef23666adc4017b767646373940d231d7c1a327) is zero.
![Screenshot-20220827001541-443x325](https://user-images.githubusercontent.com/82761650/186971533-0f519c3f-3ed5-4dc7-b075-44eebaffd28a.png)
 
Looking at the logs, the vote power is fetched from https://score.snapshot.org with a POST request. The request made for the `harmony-testnet.eth` space appears to be using the mainnet chain ID under the strategies field. Below is a copy of the request payload; the mismatch is tagged with a pound sign.
```json
{
  "jsonrpc": "2.0",
  "method": "get_vp",
  "params": {
    "address": "0x29c2eC57803f8b695f02613E5FA1749c165c5057",
    "network": "1666700000",
    "strategies": [
      {
        "name": "harmony-staking",
        "network": "1666600000", # mismatch
        "params": {
          "symbol": "ONE"
        }
      }
    ],
    "snapshot": 192690,
    "space": "harmony-testnet.eth",
    "delegation": false
  },
  "id": null
}
```

### Steps to reproduce the behavior
 - Add the private key for `0x29c2eC57803f8b695f02613E5FA1749c165c5057` to your wallet.
 - Connect MetaMask on the proposal link.
 - Choose an option and click on vote.

**Comment by ChaituVR** [comment]
Hey, @MaxMustermann2 you have to change this in your space settings :) closing this. feel free to reopen if needed

**Comment by MaxMustermann2** [comment]
Hey @ChaituVR, thanks for replying. I believe the Harmony Testnet space is [correctly configured](https://snapshot.org/#/harmony-testnet.eth/settings).
![Screenshot-20220828132012-636x420](https://user-images.githubusercontent.com/82761650/187063849-54c75280-00a2-4b07-99e8-6ddaa86a53ea.png)

Can you tell me if there is something else that needs to be changed, and please could you reopen the issue (I don't have the rights) for discussion to continue?

**Comment by ChaituVR** [comment]
I just checked this in [Playground ](https://snapshot.org/#/playground/harmony-staking?query=eyJwYXJhbXMiOnsic3ltYm9sIjoiT05FIn0sIm5ldHdvcmsiOiIxNjY2NzAwMDAwIiwic25hcHNob3QiOiIxOTI2OTAiLCJhZGRyZXNzZXMiOlsiMHgyOWMyZUM1NzgwM2Y4YjY5NWYwMjYxM0U1RkExNzQ5YzE2NWM1MDU3Il19)  and i can see voting power for this address, in the proposal above, the network is configured as harmony mainnet, 

I checked the strategies in the space settings and i see that inside strategy, network is still mainnet, please change it to testnet (click on strategy 'harmony-staking' 
and you will see option to change network )

**Comment by MaxMustermann2** [comment]
Thank you, that makes sense.
