### ISSUE TITLE
500 error code on pagination strategy using aavegotchi-agip-37-wap-ghst strategy [but works in playground]

### ISSUE THREAD

**Issue by programmablewealth** [snapshot-labs/snapshot-strategies#873]
### Expected behavior

Testing the aavegotchi-agip-37-wap-ghst strategy using the pagination strategy with the address 0x26cf02F892B04aF4Cf350539CE2C77FCF79Ec172 should return a voting power greater than 0.

### Actual behavior

Instead, it returns an error as you are casting your vote with a 500 error code in the console from the score API.

![500-server-code](https://user-images.githubusercontent.com/68889286/194805818-c7fed729-1788-4693-a884-706b86bc5167.PNG)

One thing I found strange, was the paginations strategy works fine using the playground, it only fails when calculating the voting power within a snapshot instance.

[working playground link](https://snapshot.org/#/playground/pagination?query=eyJwYXJhbXMiOnsic3ltYm9sIjoid2FwR0hTVCIsInN0cmF0ZWd5Ijp7Im5hbWUiOiJhYXZlZ290Y2hpLWFnaXAtMzctd2FwLWdoc3QiLCJwYXJhbXMiOnsic3ltYm9sIjoiR0hTVCIsImRlY2ltYWxzIjoxOCwiZ2hzdEFkZHJlc3MiOiIweDM4NUVlYWM1Y0I4NUEzOEE5YTA3QTcwYzczZTBhMzI3MUNmQjU0QTciLCJhbUdoc3RBZGRyZXNzIjoiMHgwODBiNUJGOGYzNjBGNjI0NjI4RTBmYjk2MUY0ZTY3YzllM2M3Q0YxIiwiZ2hzdEZ1ZFBvb2xJZCI6MSwiZ2hzdEtla1Bvb2xJZCI6NCwid2FwR2hzdFBvb2xJZCI6MCwiZ2hzdEZvbW9Qb29sSWQiOjIsImdoc3RGdWRBZGRyZXNzIjoiMHhmZWMyMzJjYzZmMGYzYWViMmY4MWIyNzg3YTliYzlmNmZjNzJlYTVjIiwiZ2hzdEdsdHJQb29sSWQiOjcsImdoc3RLZWtBZGRyZXNzIjoiMHhiZmFkMTYyNzc1ZWJmYjk5ODhkYjNmMjRlZjI4Y2E2YmMyZmI5MmYwIiwiZ2hzdFVzZGNQb29sSWQiOjUsIndhcEdoc3RBZGRyZXNzIjoiMHg3Mzk1OGQ0NkI3YUEyYmM5NDkyNmQ4YTIxNUZhNTYwQTVDZENBM2VBIiwiZ2hzdEFscGhhUG9vbElkIjozLCJnaHN0Rm9tb0FkZHJlc3MiOiIweDY0MWNhOGQ5NmIwMWRiMWUxNGE1ZmJhMTZiYzFlNWU1MDhhNDVmMmIiLCJnaHN0R2x0ckFkZHJlc3MiOiIweGIwRTM1NDc4YTM4OWREMjAwNTBENjZhNjdGQjc2MTY3OGFmOTk2NzgiLCJnaHN0VXNkY0FkZHJlc3MiOiIweDA5NmM1Y2NiMzNjZmM1NzMyYmNkMWYzMTk1YzEzZGJlZmM0YzgyZjQiLCJnaHN0QWxwaGFBZGRyZXNzIjoiMHhjNzY1ZWNhMGFkM2ZkMjc3NzlkMzZkMThlMzI1NTJiZDdlMjZmZDdiIiwiZ2hzdFdtYXRpY1Bvb2xJZCI6NiwiZ2hzdFdtYXRpY0FkZHJlc3MiOiIweGY2OWU5Mzc3MUYxMUFFQ2Q4RTU1NGFBMTY1QzNGZTdmZDgxMTUzMGMiLCJnbHRyU3Rha2luZ0FkZHJlc3MiOiIweDFmRTY0Njc3QWIxMzk3ZTIwQTEyMTFBRmFlMjc1ODU3MGZFYTFCOGMifX19LCJuZXR3b3JrIjoiMTM3Iiwic25hcHNob3QiOiIiLCJhZGRyZXNzZXMiOlsiMHhhNDc4YzI5NzVhYjFlYTg5ZTgxOTY4MTFmNTFhN2I3YWRlMzNlYjExIiwiMHhlRjgzMDVFMTQwYWM1MjAyMjVEQWYwNTBlMmY3MWQ1ZkJjQzU0M2U3IiwiMHgxRTFBNTFFMjVmMjgxNjMzNWNBNDM2RDY1ZTlBZjc2OTRCRTIzMmFkIiwiMHgxRjcxN0NlOGZmMDc1OTdlZTdjNDA4YjU2MjNkRjQwQWFBZjE3ODdDIiwiMHgxYzdhOTI3NUYyQkQ1YTI2MEE5YzMxMDY5Rjc3ZDUzNDczYjhhZTJlIiwiMHgxZDVFNjVhMDg3ZUJjM2QwM2EyOTQ0MTJFNDZDRTVENjg4Mjk2OWY0IiwiMHgxZjI1NDMzNkU1YzQ2NjM5QTg1MWI5Q2ZDMTY1Njk3MTUwYTZjMzI3IiwiMHgyZWMzRjgwQmVEQTYzRWRlOTZCQTIwMzc1MDMyQ0REM2FBZmIzMDMwIiwiMHg0QWNCY0E2QkUyZjhEMjU0MGJCRjRDQTc3RTQ1ZEEwQTRhMDk1RmEyIiwiMHg0RjNEMzQ4YTZEMDk4MzdBZTc5NjFCMUUwY0VlMmNjMTE4Y2VjNzc3IiwiMHg2RDdmMjNBNTA5RTIxMkJhNzc3M0VDMWIyNTA1ZDFBMTM0ZjU0ZmJlIiwiMHgwN2ExZjZmYzg5MjIzYzVlYkQ0ZTRkZGFFODlBYzk3NjI5ODU2QTBmIiwiMHg4ZDVGMDUyNzBkYTQ3MGUwMTViNjdBYjUwNDJCRGJFMkQyRkVGQjQ4IiwiMHg4ZDA3RDIyNWE3NjliN0FmM0E5MjM0ODFFMUZkRjQ5MTgwZTZBMjY1IiwiMHg4ZjYwNTAxZEU1YjliMDFGOUVBZjEyMTRkYkUxOTI0YUE5N0Y3ZmQwIiwiMHg5QjhlOGREOTE1MTI2MGMyMUNCNkQ3Y2M1OTA2N2NkOERGMzA2RDU4IiwiMHgxN2VhOTJENkZmYkFBMWM3RjZCMTE3YzFFOUQwYzg4QUJkYzhiODRDIiwiMHgzOEMwMDM5MjQ3QTMxRjM5MzliYUU2NWU5NTM2MTIxMjVjQjg4MjY4Il19)

### Steps to reproduce the behavior

Test with any address after adding the pagination strategy into a snapshot instance while using the strategy params JSON as attached.

[wapGHST json.txt](https://github.com/snapshot-labs/snapshot-strategies/files/9743629/wapGHST.json.txt)

**Comment by ChaituVR** [comment]
I see this error when I try with that address
```
Cannot read properties of undefined (reading '0')
```

But works fine when I pass other addresses, I think it is because of this>
https://github.com/snapshot-labs/snapshot-strategies/blob/master/src/strategies/aavegotchi-agip-37-wap-ghst/index.ts#L50-L54

Can raise a PR?

**Comment by programmablewealth** [comment]
yes please mate

**Comment by programmablewealth** [comment]
thanks mate. i will raise a PR and fix this bug. cheers.

**Comment by programmablewealth** [comment]
Pull request with the bug fix has been raised

https://github.com/snapshot-labs/snapshot-strategies/pull/876
