### ISSUE TITLE
Lint check a part of CI

### ISSUE THREAD

**Issue by CjHare** [snapshot-labs/snapshot-strategies#94]
### Expected behavior
Committed code should conform to the expected formatting & linting rules.

### Actual behavior
No enforcement of formatting / linting rules as part of the PR. 
When `lint` is run locally there are a number of files that get auto-fixed. 

### Steps to reproduce the behavior
The lint target uses `--fix`, when run locally on a fresh checkout I'm getting many local changes.
`npm run lint`
```shell
git status                                                                                                             
On branch linting
Your branch is up to date with 'origin/linting'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   package-lock.json
	modified:   src/strategies/balance-in-vdfyn-vault/index.ts
	modified:   src/strategies/cyberkongz/index.ts
	modified:   src/strategies/holds-tokens/index.ts
	modified:   src/strategies/hopr-bridged-balance/index.ts
	modified:   src/strategies/index.ts
	modified:   src/strategies/loot-character-guilds/index.ts
	modified:   src/strategies/mcn-farm/index.ts
	modified:   src/strategies/mstable/index.ts
	modified:   src/strategies/occ-stake-of/index.ts
	modified:   src/utils.ts
```

**Comment by CjHare** [comment]
If you'd like I can create another entry under `.github/workflows` either to run the linter without `--fix` or add that as another step in the `Test strategy` flow 🙂

**Comment by ChaituVR** [comment]
@CjHare Thanks for the Idea :) We now have an automated lint that raises a PR every week with the fixes
